### ISSUE TITLE
Login Widget Breaking on first install

### ISSUE THREAD

**Issue by fourcolors** [lens-protocol/lens-widgets#7]
I have a new remix project spun up and did:

``` yarn add @lens-protocol/widgets-react```

Followed by a react component that looks like this:

```
import { SignInWithLens, Theme, Size } from "@lens-protocol/widgets-react";

async function onSignIn(tokens, profile) {
  console.log("tokens: ", tokens);
  console.log("profile: ", profile);
}

export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <SignInWithLens onSignIn={onSignIn} />
    </div>
  );
}
```

It's giving me this error: 
```
/Users/fourcolors/Projects/hoooks/artist-dashboard/.yarn/cache/@lens-protocol-widgets-react-npm-0.0.6-1beee35485-e38eb3a2d5.zip/node_modules/@lens-protocol/widgets-react/dist/index.js:1
export { ShareToLens } from './ShareToLens';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require$$0.Module._extensions..js (/Users/fourcolors/Projects/hoooks/artist-dashboard/.pnp.cjs:22368:33)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.require$$0.Module._load (/Users/fourcolors/Projects/hoooks/artist-dashboard/.pnp.cjs:22205:14)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/fourcolors/Projects/hoooks/artist-dashboard/app/routes/_index.tsx:1:45)
```

Running:     "@lens-protocol/widgets-react": "^0.0.6",

**Comment by fourcolors** [comment]
Ok, so it looks like this error is related to my SSR with remix. 

If anyone's running Remix, you'll need to add this to your remix.config.js file:

```
module.exports = {
  serverDependenciesToBundle: ["@lens-protocol/widgets-react"],
};
```

Also, it seems like I need to install other deps to get widgets to work out of the box. Still working through those.
